version: '3'
services:

  mongodb:
    image: mongo
    ports:
      - 27016:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
      
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongodb  

  mock-app:
    image: mockoon-test
    ports:
      - 7900:3001
    command: mockoon-cli start --data ./dat.json
    
  bureau-app-try:
    build: .
    ports:
      - 8500:80
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  mongo-data:
    driver: local
